import userModel from "../models/userModel.js";
import validator from "validator";
import bcrypt from "bcrypt";
import jwt from "jsonwebtoken";

const createToken = (id) => {
    return jwt.sign({id},process.env.JWT_SECRET); // manually created token
}

// Route for user login
const loginUser = async (req,res) => {
    try {
        const {email,password} = req.body;
        
        const user = await userModel.findOne({email}); // checks and stores user with email

        if(!user) {
            return res.json({success:false, message:"User does not exist"});
        } // else, function will execute

        // boolean
        const isMatch = await bcrypt.compare(password,user.password); // user.pw = pw saved in database

        if(isMatch) {
            const token = createToken(user._id); // obtained fr database
            res.json({success:true, token});
        } else {
              res.json({success:false, message:"Invalid credentials"}); // user entered wrong pw
        }
    } catch (error) {
        console.log(error);
        res.json({success:false,message: error.message});
    }
}

// Route for user registration
const registerUser = async (req,res) => {
    // res.json({msg:"Register API Working"})
    try {

        const {name,email,password} = req.body; // receive name,email,pw

        // checking user already exists
        const exists = await userModel.findOne({email}); // email is unique
        if(exists) {
            return res.json({success:false, message:"User already exists"}); // will create response and terminate method
        }

        // check if email/pw is valid
        if(!validator.isEmail(email)) {
            return res.json({success:false, message:"Please enter a valid email"});
        }

        if(password.length < 8) {
            return res.json({success:false, message:"Please enter a strong password"});
        }

        // hashing user password
        const salt = await bcrypt.genSalt(10); // larger number = longer time to encrypt pw
        const hashedPassword = await bcrypt.hash(password, salt);

        // create new user
        const newUser = new userModel({
            name,
            email,
            password:hashedPassword
        })

        // save user into database
        const user = await newUser.save(); 
        
        const token = createToken(user._id); // autogenerated by mongoDB data base

        res.json({success:true, token}); // user successfully created

    } catch (error) { // catches any errors in creating user
        console.log(error);
        res.json({success:false,message: error.message});
    }
}

// Route for admin login
const adminLogin = async (req,res) => {
    try {
        const {email,password} = req.body;

        if(email === process.env.ADMIN_EMAIL && password === process.env.ADMIN_PASSWORD) { // check login matches
            const token = jwt.sign(email+password,process.env.JWT_SECRET); // generate token: email+pw creates on string
            res.json({success:true,token});
        } else {
            res.json({success:false,message:"Invalid credentials"});
        }

    } catch (error) {
        console.log(error);
        res.json({success:false,message: error.message});
    }
}

export {loginUser, registerUser, adminLogin}